import './globals.css'
import type { Metadata } from 'next'
import { Poppins , Roboto_Mono  } from 'next/font/google'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100','400','800']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
